import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Robert' at '29.06.16 15:34' with Gradle 2.9
 *
 * @author Robert, @date 29.06.16 15:34
 */
public class FileTest {
    @Test public void testSomeLibraryMethod() {
    JavaFile testFile = new JavaFile("Wert1", "Wert2");
    assertEquals(testFile.getName(), "Wert1");
    }
}
