import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Robert' at '29.06.16 15:34' with Gradle 2.9
 *
 * @author Robert, @date 29.06.16 15:34
 */
public class LibraryTest {
   // @Test public void testSomeLibraryMethod() {
    //    Library classUnderTest = new Library();
    //    assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
   // }
}
